--Tatapoka´s cut
DROP DATABASE CLINICA;
CREATE DATABASE CLINICA;
--BORRAR TABLAS
DROP TABLE SUCURSAL CASCADE CONSTRAINTS;
DROP TABLE CONSULTORIO CASCADE CONSTRAINTS;
DROP TABLE EQUIPAMIENTO CASCADE CONSTRAINTS;
DROP TABLE TEL_AFI CASCADE CONSTRAINTS;
DROP TABLE ODONTOLOGO_SUCURSAL CASCADE CONSTRAINTS;
DROP TABLE ODONTOLOGO CASCADE CONSTRAINTS;
DROP TABLE ODONTOLOGO_TRATAMIENTO CASCADE CONSTRAINTS;
DROP TABLE TRATAMIENTO CASCADE CONSTRAINTS;
DROP TABLE TRATAMIENTO_AFILIADO CASCADE CONSTRAINTS;
DROP TABLE AFILIACION CASCADE CONSTRAINTS;
DROP TABLE INDIVIDUAL CASCADE CONSTRAINTS;
DROP TABLE GRUPAL CASCADE CONSTRAINTS;
DROP TABLE HISTORIAL CASCADE CONSTRAINTS;
DROP TABLE CITA CASCADE CONSTRAINTS;
DROP TABLE TRATAMIENTO_SUCURSAL;
--Afiliado

CREATE TABLE AFILIACION(
idCedula CHAR(10) NOT NULL,
nombreAfi VARCHAR2(20) NOT NULL,
apePatAfi VARCHAR2(20) NOT NULL,
apeMatAfi VARCHAR2(20),
cuotaMensual NUMERIC(8,2) NOT NULL,
tipo CHAR(1) NOT NULL,--checar
CONSTRAINT PK_AFILIACION PRIMARY KEY(idCedula),
CONSTRAINT CK_AFI_TYPE CHECK (tipo IN ('i','g'))
);

CREATE TABLE INDIVIDUAL(
idCedula CHAR(10),
CONSTRAINT PK_INDIVIDUAL PRIMARY KEY(idCedula),
CONSTRAINT FK_INDIVIDUAL FOREIGN KEY(idCedula) REFERENCES AFILIACION ON DELETE CASCADE
);

CREATE TABLE GRUPAL(
idCedula CHAR(10),
nomConvenio VARCHAR2(20) NOT NULL,
rebajaProcentaje NUMERIC(4,2) NOT NULL,
CONSTRAINT PK_GRUPAL PRIMARY KEY(idCedula),
CONSTRAINT FK_GRUPAL FOREIGN KEY(idCedula) REFERENCES AFILIACION ON DELETE CASCADE,
CONSTRAINT AK_CONVENIO UNIQUE (nomConvenio)
);

CREATE TABLE TEL_AFI(
idCedula CHAR(10),
telefonoAfi NUMERIC(10),
CONSTRAINT PK_TELAFI PRIMARY KEY(idCedula,telefonoAfi),
CONSTRAINT FK_TELAFI FOREIGN KEY(idCedula) REFERENCES AFILIACION ON DELETE CASCADE
);
--Histórico

CREATE TABLE HISTORIAL(
idHist CHAR(10),
idCedula CHAR(10),
CONSTRAINT PK_HIST PRIMARY KEY(idHist),
CONSTRAINT FK_HIST FOREIGN KEY(idCedula) REFERENCES AFILIACION ON DELETE CASCADE
);
--Sucursal

CREATE TABLE SUCURSAL(
nombreSuc VARCHAR2(25),
ciudad VARCHAR2(30) NOT NULL,
calle VARCHAR2(30) NOT NULL,
numero NUMERIC(5) NOT NULL,
CONSTRAINT PK_SUCURSAL PRIMARY KEY (nombreSuc)
);

--Consultorio

CREATE TABLE CONSULTORIO(
numConsultorio NUMERIC(3),
nombreSuc VARCHAR2(25), --viene de sucursal
CONSTRAINT PK_CONSULTORIO PRIMARY KEY(nombreSuc,numConsultorio),
CONSTRAINT FK_CONSULTORIO FOREIGN KEY(nombreSuc) REFERENCES SUCURSAL ON DELETE CASCADE
);

--Equipamiento

CREATE TABLE EQUIPAMIENTO(
numSerie CHAR(10),--cambie el nombre de noSerie a numSerie para que todos los numeros se represente como num
nombreEquip VARCHAR2(20) NOT NULL,
fechaMantenimiento DATE NOT NULL,
numConsultorio NUMERIC(3),
nombreSuc VARCHAR2(25),
CONSTRAINT PK_EQUIPAMIENTO PRIMARY KEY(numSerie),
CONSTRAINT FK_EQUIPAMIENTO FOREIGN KEY(nombreSuc,numConsultorio) REFERENCES CONSULTORIO ON DELETE SET NULL
);

--Odontologo

CREATE TABLE ODONTOLOGO(
cedulaOdont CHAR(10) NOT NULL,
nombreOdont VARCHAR2(20) NOT NULL,
apPatOdont VARCHAR2(20) NOT NULL,
apMatOdont VARCHAR2(20),
--tratamientoOdont VARCHAR2(20),--CREO QUE EN ELLA SE PONIA UNA CS1
especialidad VARCHAR2(20) NOT NULL,
--horaAten DATE,
CONSTRAINT PK_ODONTOLOGO PRIMARY KEY(cedulaOdont) 
);

--RELACION ODONTÓLOGO SUCURSAL

CREATE TABLE ODONTOLOGO_SUCURSAL(
nombreSuc VARCHAR2(25),
cedulaOdont CHAR(10),
horario TIMESTAMP NOT NULL,
CONSTRAINT PK_SUC_ODONT PRIMARY KEY(nombreSuc,cedulaOdont,horario),
CONSTRAINT FK_SUC_ODONT_ODO FOREIGN KEY(cedulaOdont) REFERENCES ODONTOLOGO ON DELETE CASCADE,
CONSTRAINT FK_SUC_ODONT_SUC FOREIGN KEY(nombreSuc) REFERENCES SUCURSAL ON DELETE CASCADE
);

--Tratamiento

CREATE TABLE TRATAMIENTO(
nombreTratamiento VARCHAR2(25) NOT NULL,
costoTratamiento NUMERIC(8,2) NOT NULL,
CONSTRAINT PK_TRATAMIENTO PRIMARY KEY(nombreTratamiento)
);

--Relaciones con Tratamiento

CREATE TABLE ODONTOLOGO_TRATAMIENTO(
idOdoTrat NUMERIC,
cedulaOdont CHAR(10) NOT NULL,
nombreTratamiento VARCHAR2(25) NOT NULL,--CHECAR
CONSTRAINT PK_ODONTOLOGO_TRATAMIENTO PRIMARY KEY (idOdoTrat),
CONSTRAINT FK_ODONTOLOGO_TRATAMIENTO_ODO FOREIGN KEY(cedulaOdont) REFERENCES ODONTOLOGO ON DELETE CASCADE,
CONSTRAINT FK_ODONTOLOGO_TRATAMIENTO_TRAT FOREIGN KEY(nombreTratamiento) REFERENCES TRATAMIENTO ON DELETE CASCADE
);

CREATE TABLE TRATAMIENTO_AFILIADO(
idCedula CHAR(10),
idOdoTrat NUMERIC,
fechaInicio DATE  NOT NULL,
finalizado CHAR(1)  NOT NULL,--CHECAR
pagoTratamiento NUMERIC(8,2)  NOT NULL,
idHist CHAR(10) DEFAULT '0000000000' NOT NULL,
CONSTRAINT PK_TRATAMIENTO_AFILIADO PRIMARY KEY(idCedula,idOdoTrat,fechaInicio),
CONSTRAINT FK_TRATAMIENTO_AFILIADO_AFI FOREIGN KEY(idCedula) REFERENCES AFILIACION ON DELETE CASCADE,
CONSTRAINT FK_TRATAMIENTO_AFILIADO_ODO_TRAT FOREIGN KEY(idOdoTrat) REFERENCES ODONTOLOGO_TRATAMIENTO ON DELETE SET NULL,
CONSTRAINT FK_TRATAMIENTO_AFILIADO_HIST FOREIGN KEY(idHist) REFERENCES HISTORIAL ON DELETE CASCADE,
CONSTRAINT CK_TRATAMIENTO_ENDED CHECK (finalizado IN ('s','n'))
);

CREATE TABLE TRATAMIENTO_SUCURSAL(
nombreTratamiento VARCHAR2(25),
nombreSuc VARCHAR2(25),
CONSTRAINT PK_TRATAMIENTO_SUCURSAL PRIMARY KEY(nombreTratamiento,nombreSuc),
CONSTRAINT FK_TRATAMIENTO_SUCURSAL_TRAT FOREIGN KEY(nombreTratamiento) REFERENCES TRATAMIENTO ON DELETE CASCADE,
CONSTRAINT FK_TRATAMIENTO_SUCURSAL_SUC FOREIGN KEY(nombreSuc) REFERENCES SUCURSAL ON DELETE CASCADE
);

CREATE TABLE CITA(
idCita NUMERIC,
idHist CHAR(10),
idCedula CHAR(10) NOT NULL,
nombreSuc VARCHAR2(25)  NOT NULL,
cedulaOdont CHAR(10) NOT NULL,
fechaCita DATE NOT NULL,
numConsultorio NUMERIC(3) NOT NULL,
finalizadoCita CHAR(1) NOT NULL,
CONSTRAINT FK_CITA_HITS FOREIGN KEY (idHist) REFERENCES HISTORIAL ON DELETE CASCADE,
CONSTRAINT FK_CITA_SUC FOREIGN KEY (nombreSuc) REFERENCES SUCURSAL ON DELETE SET NULL,
CONSTRAINT FK_CITA_ODON FOREIGN KEY (cedulaOdont) REFERENCES ODONTOLOGO ON DELETE SET NULL,
CONSTRAINT FK_CITA_CONSUL FOREIGN KEY(nombreSuc,numConsultorio) REFERENCES CONSULTORIO ON DELETE SET NULL,
CONSTRAINT PK_CITA PRIMARY KEY (idCita),
CONSTRAINT CK_CITA_ENDED CHECK (finalizadoCita IN ('s','n'))
);

