--Tatapoka´s cut
DROP DATABASE CLINICA;
CREATE DATABASE CLINICA;
--BORRAR TABLAS
DROP TABLE SUCURSAL CASCADE CONSTRAINTS;
DROP TABLE CONSULTORIO CASCADE CONSTRAINTS;
DROP TABLE EQUIPAMIENTO CASCADE CONSTRAINTS;
DROP TABLE TEL_AFI CASCADE CONSTRAINTS;
DROP TABLE ODONTOLOGO_SUCURSAL CASCADE CONSTRAINTS;
DROP TABLE ODONTOLOGO CASCADE CONSTRAINTS;
DROP TABLE ODONTOLOGO_TRATAMIENTO CASCADE CONSTRAINTS;
DROP TABLE TRATAMIENTO CASCADE CONSTRAINTS;
DROP TABLE TRATAMIENTO_AFILIADO CASCADE CONSTRAINTS;
DROP TABLE AFILIACION CASCADE CONSTRAINTS;
DROP TABLE INDIVIDUAL CASCADE CONSTRAINTS;
DROP TABLE GRUPAL CASCADE CONSTRAINTS;
DROP TABLE HISTORIAL CASCADE CONSTRAINTS;
--Afiliado

CREATE TABLE AFILIACION(
idCedula CHAR(10),
nombreAfi VARCHAR2(20),
apePatAfi VARCHAR2(20),
apeMatAfi VARCHAR2(20),
cuotaMensual NUMERIC(8,2),
tipo CHAR(1),--checar
CONSTRAINT PK_AFILIACION PRIMARY KEY(idCedula),
CONSTRAINT CK_AFI_TYPE CHECK (tipo IN ('i','g'))
);

CREATE TABLE INDIVIDUAL(
idCedula CHAR(10),
CONSTRAINT PK_INDIVIDUAL PRIMARY KEY(idCedula),
CONSTRAINT FK_INDIVIDUAL FOREIGN KEY(idCedula) REFERENCES AFILIACION
);

CREATE TABLE GRUPAL(
idCedula CHAR(10),
nomConvenio VARCHAR2(20),
rebajaProcentaje NUMERIC(8,2),
CONSTRAINT PK_GRUPAL PRIMARY KEY(idCedula),
CONSTRAINT FK_GRUPAL FOREIGN KEY(idCedula) REFERENCES AFILIACION
);

CREATE TABLE TEL_AFI(
idCedula CHAR(10),
telefonoAfi NUMERIC(10),
CONSTRAINT PK_TELAFI PRIMARY KEY(idCedula,telefonoAfi),
CONSTRAINT FK_TELAFI FOREIGN KEY(idCedula) REFERENCES AFILIACION
);
--Histórico

CREATE TABLE HISTORIAL(
idHist CHAR(10),
idCedula CHAR(10),
CONSTRAINT PK_HIST PRIMARY KEY(idHist),
CONSTRAINT FK_HIST FOREIGN KEY(idCedula) REFERENCES AFILIACION
);
--Sucursal

CREATE TABLE SUCURSAL(
nombreSuc VARCHAR2(20),
ciudad VARCHAR2(20),
calle VARCHAR2(20),
numero NUMERIC(5),
CONSTRAINT PK_SUCURSAL PRIMARY KEY (nombreSuc)
);

--Consultorio

CREATE TABLE CONSULTORIO(
numConsultorio NUMERIC(3),
nombreSuc VARCHAR2(20), --viene de sucursal
CONSTRAINT PK_CONSULTORIO PRIMARY KEY(nombreSuc,numConsultorio),
CONSTRAINT FK_CONSULTORIO FOREIGN KEY(nombreSuc) REFERENCES SUCURSAL
);

--Equipamiento

CREATE TABLE EQUIPAMIENTO(
numSerie CHAR(10),--cambie el nombre de noSerie a numSerie para que todos los numeros se represente como num
nombreEquip VARCHAR2(20),
fechaMantenimiento DATE,
numConsultorio NUMERIC(3),
nombreSuc VARCHAR2(20),
CONSTRAINT PK_EQUIPAMIENTO PRIMARY KEY(numSerie),
CONSTRAINT FK_EQUIPAMIENTO FOREIGN KEY(nombreSuc,numConsultorio) REFERENCES CONSULTORIO
);

--Odontologo

CREATE TABLE ODONTOLOGO(
cedulaOdont CHAR(10),
nombreOdont VARCHAR2(20),
apPatOdont VARCHAR2(20),
apMatOdont VARCHAR2(20),
--tratamientoOdont VARCHAR2(20),--CREO QUE EN ELLA SE PONIA UNA CS1
especialidad VARCHAR2(20),
--horaAten DATE,
CONSTRAINT PK_ODONTOLOGO PRIMARY KEY(cedulaOdont) 
);

--RELACION ODONTÓLOGO SUCURSAL

CREATE TABLE ODONTOLOGO_SUCURSAL(
nombreSuc VARCHAR2(20),
cedulaOdont CHAR(10),
horario DATE,
CONSTRAINT PK_SUC_ODONT PRIMARY KEY(nombreSuc,cedulaOdont,horario),
CONSTRAINT FK_SUC_ODONT_ODO FOREIGN KEY(cedulaOdont) REFERENCES ODONTOLOGO,
CONSTRAINT FK_SUC_ODONT_SUC FOREIGN KEY(nombreSuc) REFERENCES SUCURSAL,
CONSTRAINT AK_SUC_ODONT UNIQUE (horario)
);

--Tratamiento

CREATE TABLE TRATAMIENTO(
nombreTratamiento VARCHAR2(10),
costoTratamiento NUMERIC(8,2),
CONSTRAINT PK_TRATAMIENTO PRIMARY KEY(nombreTratamiento)
);

--Relaciones con Tratamiento

CREATE TABLE ODONTOLOGO_TRATAMIENTO(
idOdoTrat NUMERIC,
cedulaOdont CHAR(10),
nombreTratamiento VARCHAR2(10),--CHECAR
CONSTRAINT PK_ODONTOLOGO_TRATAMIENTO PRIMARY KEY (idOdoTrat),
CONSTRAINT FK_ODONTOLOGO_TRATAMIENTO_ODO FOREIGN KEY(cedulaOdont) REFERENCES ODONTOLOGO,
CONSTRAINT FK_ODONTOLOGO_TRATAMIENTO_TRAT FOREIGN KEY(nombreTratamiento) REFERENCES TRATAMIENTO
);

CREATE TABLE TRATAMIENTO_AFILIADO(
idCedula CHAR(10),
idOdoTrat NUMERIC,
fechaInicio DATE,
finalizado CHAR(1),--CHECAR
pagoTratamiento NUMERIC(8,2),
idHist CHAR(10),
CONSTRAINT PK_TRATAMIENTO_AFILIADO PRIMARY KEY(idCedula,idOdoTrat),
CONSTRAINT FK_TRATAMIENTO_AFILIADO_AFI FOREIGN KEY(idCedula) REFERENCES AFILIACION,
CONSTRAINT FK_TRATAMIENTO_AFILIADO_ODO_TRAT FOREIGN KEY(idOdoTrat) REFERENCES ODONTOLOGO_TRATAMIENTO,
CONSTRAINT FK_TRATAMIENTO_AFILIADO_HIST FOREIGN KEY(idHist) REFERENCES HISTORIAL
);

CREATE TABLE CITA(
idCita NUMERIC,
idHist CHAR(10),
nombreSuc VARCHAR2(20),
cedulaOdont CHAR(10),
fechaCita DATE,
numConsultorio NUMERIC(3),
finalizadoCita CHAR(1),
CONSTRAINT FK_CITA_HITS FOREIGN KEY (idHist) REFERENCES HISTORIAL,
CONSTRAINT FK_CITA_SUC FOREIGN KEY (nombreSuc) REFERENCES SUCURSAL,
CONSTRAINT FK_CITA_ODON FOREIGN KEY (cedulaOdont) REFERENCES ODONTOLOGO,
CONSTRAINT FK_CITA_CONSUL FOREIGN KEY(nombreSuc,numConsultorio) REFERENCES CONSULTORIO,
CONSTRAINT PK_CITA PRIMARY KEY (idCita)
);

